title: Lorenzo Lorgna
logo: /assets/img/id_photo.jpeg
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
url: https://lorenzlorg.github.io
