title: Lorenzo Lorgna
logo: assets/img/IMG_0011.png
description:
  <p align="center">
  Milan, Italy
  <br> (+39) 3398934904
  <br> lorenzlorg@gmail.com
  <br> <a href="assets/pdf/Lorenzo_resume.pdf">Resume</a> |
  <a href="https://linkedin.com/in/lorenzo-lorgna/">LinkedIn</a> |
  <a href="https://github.com/lorenzlorg">GitHub</a> 
  </p>
# show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
url: https://lorenzlorg.github.io
github_username: lorenzlorg
# avatar: /assets/img/logo.png
# round-avatar: true

